# Generated by Django 5.0 on 2024-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_cover_img_alter_news_news_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_sections',
            field=models.ManyToManyField(related_name='news_section', to='news.newssection', verbose_name='Новостные секции'),
        ),
    ]
