# Generated by Django 5.0 on 2024-02-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_newssection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssection',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название секции'),
        ),
    ]
