# Generated by Django 5.0 on 2024-03-14 13:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
    ]
