# Generated by Django 5.0 on 2024-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_sections',
            field=models.ManyToManyField(related_name='blog_sections', to='blog.blogssection', verbose_name='Секции блога'),
        ),
    ]
