# Generated by Django 5.0 on 2023-12-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
