# Generated by Django 5.0 on 2024-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_information', '0002_somefacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somefacts',
            name='description',
            field=models.TextField(),
        ),
    ]
