# Generated by Django 5.0 on 2024-01-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_information', '0003_alter_somefacts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutresource',
            name='file',
            field=models.FileField(upload_to='./video', verbose_name='Загрузка видеофайла'),
        ),
        migrations.AlterField(
            model_name='aboutresource',
            name='image',
            field=models.ImageField(upload_to='./preview_img'),
        ),
    ]
