# Generated by Django 5.0 on 2024-01-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_information', '0004_alter_aboutresource_file_alter_aboutresource_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutresource',
            options={'verbose_name': 'Блок "О ресурсе"', 'verbose_name_plural': 'Блок "О ресурсе"'},
        ),
        migrations.AlterModelOptions(
            name='somefacts',
            options={'verbose_name': 'Блок "Немного фактов"', 'verbose_name_plural': 'Блок "Немного фактов"'},
        ),
        migrations.AlterField(
            model_name='aboutresource',
            name='data_add_video',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео'),
        ),
        migrations.AlterField(
            model_name='aboutresource',
            name='description',
            field=models.TextField(verbose_name='Описание ресурса'),
        ),
        migrations.AlterField(
            model_name='aboutresource',
            name='file',
            field=models.FileField(upload_to='./video', verbose_name='Видео о ресурсе'),
        ),
        migrations.AlterField(
            model_name='aboutresource',
            name='image',
            field=models.ImageField(upload_to='./preview_img', verbose_name='Превью-картинка для видео'),
        ),
        migrations.AlterField(
            model_name='aboutresource',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название ресурса'),
        ),
        migrations.AlterField(
            model_name='somefacts',
            name='description',
            field=models.TextField(verbose_name='Определение термина или описание факта'),
        ),
    ]
