# Generated by Django 5.0 on 2024-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='practice',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Практика/опыт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sphere_of_interest',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера интересов'),
        ),
        migrations.AlterField(
            model_name='teammemberspeciality',
            name='speciality',
            field=models.CharField(max_length=100, verbose_name='Специализация'),
        ),
    ]
