# Generated by Django 5.0 on 2024-03-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccategory',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='URL'),
        ),
    ]
