# Generated by Django 5.0 on 2024-03-17 12:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docum_app', '0003_alter_doccategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycontent',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
    ]
