# Generated by Django 5.0 on 2024-03-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum_app', '0004_alter_categorycontent_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycontent',
            options={'verbose_name': 'Статья подкатегорий документации', 'verbose_name_plural': 'Статьи подкатегорий документации'},
        ),
        migrations.RemoveField(
            model_name='categorycontent',
            name='doc_categories',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок подкатегории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание подкатегории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/sub_category', verbose_name='Видео')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='img/sub_category', verbose_name='Картинка, покрывающая видео')),
                ('doc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docum_app.doccategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='categorycontent',
            name='sub_categories',
            field=models.ManyToManyField(to='docum_app.subcategory', verbose_name='Связанные подкатегории'),
        ),
    ]
